iter9
IgorViskov/go_33_shortener pull request #9
Opened 2024-08-21 20:25 UTC by IgorViskov

2024-08-23 18:53 UTC, nburunova requested changes

2024-08-23 18:53 UTC, nburunova commented on internal/app/server_builder.go
> +var compressContentTypes = hashset.New("plain/text", "application/json", "application/x-gzip")
Функция сжатия должна работать для контента с типами application/json и text/html . Если хочешь, оставь plain/text и application/x-gzip, однако добавь "text/html"

2024-08-23 18:53 UTC, nburunova commented on internal/app/server_builder.go
> +var compressContentTypes = hashset.New("plain/text", "application/json", "application/x-gzip")
[minor] вместо добавления зависимости от hashset можно использовать slices.Contains() https://pkg.go.dev/slices#Contains

2024-08-23 18:53 UTC, nburunova commented on internal/storage/hybrid.go
> +func (s *HybridStorage) Close() error {
не вызывается, файл должен закрываться по завершению работы приложения

2024-08-25 12:00 UTC, IgorViskov commented on internal/app/server_builder.go
> +var compressContentTypes = hashset.New("plain/text", "application/json", "application/x-gzip")
Добавил

2024-08-25 12:01 UTC, IgorViskov commented on internal/config/config.go
> +func exists(path string) error {
Переименовал, нам нужно проверить не только его существование, но и хватает ли нам прав на открытые его на чтение запись

2024-08-25 12:02 UTC, IgorViskov commented on internal/storage/hybrid.go
> +func (s *HybridStorage) Close() error {
Сделал, но пока не понимаю как можно убедится в полном закрытии если приложение ловит [syscall exit](http://linux.die.net/man/2/exit)

2024-08-25 12:03 UTC, IgorViskov commented on internal/app/server_builder.go
> +var compressContentTypes = hashset.New("plain/text", "application/json", "application/x-gzip")
Переделал на слайс

2024-08-26 11:21 UTC, nburunova approved these changes

2024-08-26 11:46 UTC, merged